[package]
name = "risingwave_expr_impl"
description = "RisingWave function implementations."
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["chrono-tz", "futures-async-stream"]

[features]
udf = ["arrow-udf-runtime", "tonic", "ginepro", "zstd"]

[dependencies]
aho-corasick = "1"
anyhow = "1"
arrow-udf-runtime = { workspace = true, optional = true }
async-trait = "0.1"
auto_enums = { workspace = true }
bytes = "1"
# The feature setting is also used in src/expr/impl/src/udf/wasm.rs
chrono = { workspace = true, features = [
    "clock",
    "std",
] }
chrono-tz = { version = "0.10", features = ["case-insensitive"] }
constant_time_eq = "0.4"
educe = "0.6"
fancy-regex = "0.14"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
futures-util = "0.3"
ginepro = { version = "0.8", optional = true }
hex = "0.4"
hmac = "0.12"
iceberg = { workspace = true }
itertools = { workspace = true }
jsonbb = { workspace = true }
linkme = { workspace = true }
md5 = "0.7"
moka = { version = "0.12.0", features = ["sync"] }
num-traits = "0.2"
openssl = "0.10.72"
regex = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_estimate_size = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_sqlparser = { workspace = true }
rust_decimal = { version = "1", features = ["db-postgres", "maths"] }
self_cell = "1.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
sha2 = "0.10"
smallvec = { workspace = true }
sql-json-path = { version = "0.1", features = ["jsonbb"] }
thiserror = "1"
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = ["time"] }
# For arrow-udf-runtime/remote
tonic = { version = "0.12", optional = true }
tracing = "0.1"
zstd = { version = "0.13", default-features = false, optional = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
criterion = { workspace = true }
expect-test = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "macros",
] }

[[bench]]
name = "expr"
harness = false

[lints]
workspace = true
