[package]
name = "risingwave_expr_impl"
description = "RisingWave function implementations."
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["workspace-hack", "ctor"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack", "ctor"]

[features]
external-udf = ["arrow-udf-flight", "arrow-flight", "tonic"]
js-udf = ["arrow-udf-js"]
python-udf = ["arrow-udf-python"]
wasm-udf = ["arrow-udf-wasm", "zstd"]

[dependencies]
aho-corasick = "1"
anyhow = "1"
arrow-flight = { workspace = true, optional = true }
arrow-udf-flight = { workspace = true, optional = true }
arrow-udf-js = { workspace = true, optional = true }
arrow-udf-python = { workspace = true, optional = true }
arrow-udf-wasm = { workspace = true, optional = true }
async-trait = "0.1"
auto_enums = { workspace = true }
bytes = "1"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
chrono-tz = { version = "0.9", features = ["case-insensitive"] }
educe = "0.6"
fancy-regex = "0.13"
futures-async-stream = { workspace = true }
futures-util = "0.3"
ginepro = "0.7" # TODO(http-bump): bump to 0.8 once arrow-udf switches to tonic 0.12
hex = "0.4"
icelake = { workspace = true }
itertools = { workspace = true }
jsonbb = { workspace = true }
linkme = { version = "0.3", features = ["used_linker"] }
md5 = "0.7"
moka = { version = "0.12.0", features = ["sync"] }
num-traits = "0.2"
openssl = "0.10"
regex = "1"
risingwave_common = { workspace = true }
risingwave_common_estimate_size = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_sqlparser = { workspace = true }
rust_decimal = { version = "1", features = ["db-postgres", "maths"] }
self_cell = "1.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
sha2 = "0.10"
smallvec = "1"
sql-json-path = { version = "0.1", features = ["jsonbb"] }
thiserror = "1"
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = ["time"] }
# For arrow-udf-flight
# TODO(http-bump): bump once arrow-udf switches to tonic 0.12
tonic = { version = "0.12", optional = true }
tracing = "0.1"
zstd = { version = "0.13", default-features = false, optional = true }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
criterion = { workspace = true }
expect-test = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "macros",
] }

[[bench]]
name = "expr"
harness = false

[lints]
workspace = true
