[package]
name = "risingwave_expr"
version = "0.1.7"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "0.7"
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
byteorder = "1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
crc32fast = "1"
either = "1"
itertools = "0.10"
lazy_static = "1"
log = "0.4"
lru = "0.7"
madsim = "=0.2.0-alpha.3"
md5 = "0.7.0"
memcomparable = { path = "../utils/memcomparable" }
num-traits = "0.2"
paste = "1"
prost = "0.10"
risingwave_common = { path = "../common" }
risingwave_pb = { path = "../prost" }
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
smallvec = "1"
thiserror = "1"
tokio = { version = "=0.2.0-alpha.3", package = "madsim-tokio", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal"] }
tokio-stream = "0.1"
toml = "0.5"
tonic = { version = "=0.2.0-alpha.3", package = "madsim-tonic" }
value-encoding = { path = "../utils/value-encoding" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
