[package]
name = "risingwave_expr"
version = "0.1.5"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
byteorder = "1"
bytes = "1"
chrono = "0.4"
crc32fast = "1"
either = "1"
itertools = "0.10"
lazy_static = "1"
log = "0.4"
lru = "0.7"
memcomparable = { path = "../utils/memcomparable" }
num-traits = "0.2"
paste = "1"
prettytable-rs = "0.8"
prost = "0.10"
risingwave_common = { path = "../common" }
risingwave_pb = { path = "../prost" }
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
smallvec = "1"
thiserror = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal"] }
tokio-stream = "0.1"
toml = "0.5"
tonic = "0.7"
value-encoding = { path = "../utils/value-encoding" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
