[package]
name = "udf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
arrow-udf = "0.5.3"
#using a fixed chrono version 0.4.39 because the
#latest 0.4.40 failed to compile
chrono = "=0.4.39"
rust_decimal = "1"
serde_json = "1"

[package.metadata.cargo-machete]
ignored = ["chrono"]
