[package]
name = "udf"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
arrow-udf = "0.5"
#using a fixed chrono version 0.4.39 because the
#latest 0.4.40 failed to compile
chrono = "=0.4.39"
genawaiter = "0.99"
rust_decimal = "1"
serde_json = "1"
# 0.2.12 failed to compile with nightly-2024-10-11
libm = "=0.2.13"

[package.metadata.cargo-machete]
ignored = ["chrono"]
