[package]
name = "stats_alloc"
version = "0.1.12"
edition = "2021"
description = "Allocator with statistics"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
