version: 2
updates:
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  # Disable auto rebase to reduce cost. Use `@dependabot rebase` manually instead.
  rebase-strategy: "disabled"
  ignore:
    # Ignore patch to reduce spam. Manually run `cargo update` regularly instead.
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
    # Ignore arrow crates. It does major releases frequently: https://github.com/apache/arrow-rs/issues/5368
    # We depend on arrow directly, and also many other crates depending on arrow, including icelake, deltalake, arrow-udf, ...
    # It will always need human intervention, and we'd better be the last one to update arrow.
    - dependency-name: "arrow*"
      update-types: ["version-update:semver-minor", "version-update:semver-major"]
    - dependency-name: "parquet"
      update-types: ["version-update:semver-minor", "version-update:semver-major"]
  # Create a group of dependencies to be updated together in one pull request
  groups:
    aws:
      patterns:
        - "aws*"
    tonic:
      patterns:
        - "tonic*"
        - "prost*"
    opentelemetry:
      patterns:
        - "opentelemetry"
        - "opentelemetry*"
        - "tracing-opentelemetry"
    mysql:
      patterns:
        - "mysql_common"
        - "mysql_async"
    google-cloud:
      patterns:
        - "google-cloud*"

# Don't update these directories
- package-ecosystem: cargo
  directory: /integration_tests/feature-store
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: "*"

- package-ecosystem: maven
  directory: /java
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 5
  # Disable auto rebase to reduce cost. Use `@dependabot rebase` manually instead.
  rebase-strategy: "disabled"
  ignore:
    # Do not bump Debezium because we have hacked its source code e.g. #18760
    - dependency-name: "io.debezium:*"
      update-types:
        ["version-update:semver-minor", "version-update:semver-major"]
    # Don't upgrade protobuf to 4.x now. See https://github.com/grpc/grpc-java/issues/11015
    - dependency-name: "com.google.protobuf:*"
      update-types:
        ["version-update:semver-major"]
    # Let's do major version updates manually
    - dependency-name: "*"
      update-types:
        ["version-update:semver-major"]
  groups:
    # Group all dependenies together because Java libraries are quite stable
    all:
      patterns:
        - "*"

# Don't touch risingwave-sink-deltalake-test. It's too complicated and it's only for testing
- package-ecosystem: maven
  directory: /java/connector-node/risingwave-sink-deltalake-test/
  schedule:
    interval: "weekly"
  ignore:
    - dependency-name: "*"