# Usage: install pre-commit, and then run `pre-commit install` to install git hooks
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
        exclude: 'src/frontend/planner_test/tests/testdata/.*'
    -   id: trailing-whitespace
-   repo: https://github.com/crate-ci/typos
    rev: v1.23.1
    hooks:
      - id: typos
-   repo: local
    hooks:
    -   id: rustfmt
        name: rustfmt
        entry: rustfmt --edition 2021
        language: system
        types: [rust]
    -   id: cargo sort
        name: cargo sort
        entry: cargo sort -g -w
        language: system
        files: 'Cargo.toml'
        pass_filenames: false
