[default.extend-words]
indexs = "indices"
Stichting = "Stichting"
fo = "fo"
FPR = "FPR"
ot = "ot"
inout = "inout"
numer = "numer"
nd = "nd"
steam = "stream"

[files]
extend-exclude = [
    "src/tests/regress/data",
    "e2e_test",
    "**/*.svg",
    "scripts",
    "src/frontend/planner_test/tests/testdata",
    "src/tests/sqlsmith/tests/freeze",
    "src/workspace-hack/Cargo.toml"
    "**/go.mod",
    "**/go.sum",
]
