[package]
name = "memcomparable"
version = "0.1.12"
edition = "2021"
description = "Memcomparable format."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
rand = "0.8"
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
