[package]
name = "simple_web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etcd-client = "0.10"
tokio = { version = "1.0", features = ["full"] }

