[package]
name = "risingwave_backup"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1"
async-trait = "0.1"
bytes = { version = "1", features = ["serde"] }
itertools = { workspace = true }
parking_lot = { workspace = true }
prost = { workspace = true }
risingwave_common = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_meta_model = { workspace = true }
risingwave_object_store = { workspace = true }
risingwave_pb = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
twox-hash = "2"

[dev-dependencies]
risingwave_hummock_sdk = { workspace = true }

[lints]
workspace = true
