[package]
name = "risingwave_pb"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
pbjson = "0.5"
prost = "0.11"
prost-helpers = { path = "helpers" }
serde = { version = "1", features = ["derive"] }
tonic = { version = "0.2.14", package = "madsim-tonic" }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[build-dependencies]
pbjson-build = "0.5"
tonic-build = { version = "0.2.11", package = "madsim-tonic-build" }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]
