[package]
name = "risingwave_pb"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["enum-as-inner", "pbjson", "prost-helpers", "strum"]

[dependencies]
enum-as-inner = "0.7"
paste = "1"
pbjson = "0.9"
prost = { workspace = true }
prost-helpers = { path = "helpers" }
risingwave_error = { workspace = true }
sea-orm  = { workspace = true }
serde = { workspace = true }
strum = { version = "0.28", features = ["derive"] }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tonic = { workspace = true }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
static_assertions = "1"

[build-dependencies]
fs-err = "3.2"
pbjson-build = "0.9"
prost-build = { workspace = true }
tonic-build = { workspace = true }
walkdir = "2"

[lints]
workspace = true
