[package]
name = "risingwave_test_runner"
version = "0.2.0-alpha"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fail = "0.5"
sync-point = { path = "../utils/sync-point" }
workspace-hack = { version = "0.2.0-alpha", path = "../workspace-hack" }
