---
version: "3"
services:
  compactor-0:
    extends:
      file: docker-compose.yml
      service: compactor-0
    depends_on:
      - meta-node-0
    env_file: multiple_object_storage.env
  compute-node-0:
    extends:
      file: docker-compose.yml
      service: compute-node-0
    depends_on:
      - meta-node-0
    env_file: multiple_object_storage.env
  etcd-0:
    extends:
      file: docker-compose.yml
      service: etcd-0
  frontend-node-0:
    extends:
      file: docker-compose.yml
      service: frontend-node-0
    depends_on:
      - meta-node-0
  grafana-0:
    extends:
      file: docker-compose.yml
      service: grafana-0
  meta-node-0:
    extends:
      file: docker-compose.yml
      service: meta-node-0
    command:
      - meta-node
      - "--listen-addr"
      - "0.0.0.0:5690"
      - "--advertise-addr"
      - "meta-node-0:5690"
      - "--dashboard-host"
      - "0.0.0.0:5691"
      - "--prometheus-host"
      - "0.0.0.0:1250"
      - "--backend"
      - etcd
      - "--etcd-endpoints"
      - "etcd-0:2388"
      - "--connector-rpc-endpoint"
      - "connector-node:50051"
      - "--state-store"
      - "hummock+azblob://<container_name>"
      - "--data-directory"
      - "hummock_001"
      - "--config-path"
      - /risingwave.toml
    depends_on:
      - etcd-0
    env_file: multiple_object_storage.env
  prometheus-0:
    extends:
      file: docker-compose.yml
      service: prometheus-
  connector-node:
    extends:
      file: docker-compose.yml
      service: connector-node
  message_queue:
    extends:
      file: docker-compose.yml
      service: message_queue
volumes:
  etcd-0:
    external: false
  grafana-0:
    external: false
  prometheus-0:
    external: false
  message_queue:
    external: false
