version: "3"
services:
  minio:
    container_name: minio_container
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      - "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  miniocreatebuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " until (mc alias set hummock-minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY) do echo '...waiting...' && sleep 1; done; mc admin user add hummock-minio/ hummock 12345678; mc admin policy set hummock-minio/ readwrite user=hummock; mc mb hummock-minio/hummock001; exit 0; "
  metanode:
    container_name: metanode_container
    image: ghcr.io/singularity-data/meta-node:latest
    command: --host 0.0.0.0:5690 --dashboard-host 0.0.0.0:5691 --prometheus-host 0.0.0.0:1250
    expose:
      - "5690"
      - "5691"
      - "1250"
  computenode:
    container_name: computenode_container
    image: ghcr.io/singularity-data/compute-node:latest
    command: --config-path /risingwave/config/risingwave.toml --client-address computenode:5688 --host 0.0.0.0:5688 --prometheus-listener-addr 0.0.0.0:1222 --metrics-level 1 --state-store hummock+minio://hummock:12345678@minio:9000/hummock001 --meta-address http://metanode:5690
    expose:
      - "5688"
      - "1222"
    volumes:
      - ./src/config:/risingwave/config
    depends_on:
      - metanode
  frontend:
    container_name: frontend_container
    image: ghcr.io/singularity-data/frontend-node:latest
    command: --client-address frontend:4566 --host 0.0.0.0:4566 --meta-addr http://metanode:5690
    ports:
      - "4566:4566"
    depends_on:
      - metanode
      - computenode
  redpanda:
    container_name: redpanda_container
    image: docker.vectorized.io/vectorized/redpanda:latest
    command: redpanda start --smp 1 --reserve-memory 0M --overprovisioned --node-id 0 --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092 --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"
