---
version: "3"
services:
  compactor-0:
    image: "ghcr.io/risingwavelabs/risingwave:nightly-20220620"
    command:
      - compactor-node
      - "--host"
      - "0.0.0.0:6660"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1260"
      - "--metrics-level"
      - "1"
      - "--state-store"
      - "hummock+minio://hummockadmin:hummockadmin@minio-0:9301/hummock001"
      - "--meta-address"
      - "http://meta-node-0:5690"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "6660"
      - "1260"
    ports: []
    depends_on:
      - meta-node-0
      - minio-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
    container_name: compactor-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/6660
      interval: 1s
      timeout: 5s
      retries: 5
  compute-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:nightly-20220620"
    command:
      - compute-node
      - "--host"
      - "0.0.0.0:5688"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1222"
      - "--client-address"
      - "compute-node-0:5688"
      - "--metrics-level"
      - "1"
      - "--state-store"
      - "hummock+minio://hummockadmin:hummockadmin@minio-0:9301/hummock001"
      - "--meta-address"
      - "http://meta-node-0:5690"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "5688"
      - "1222"
    ports: []
    depends_on:
      - meta-node-0
      - minio-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
    container_name: compute-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5688
      interval: 1s
      timeout: 5s
      retries: 5
  etcd-0:
    image: "quay.io/coreos/etcd:latest"
    command:
      - /usr/local/bin/etcd
      - "--listen-client-urls"
      - "http://0.0.0.0:2388"
      - "--advertise-client-urls"
      - "http://etcd-0:2388"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2389"
      - "--initial-advertise-peer-urls"
      - "http://etcd-0:2389"
      - "--listen-metrics-urls"
      - "http://0.0.0.0:2379"
      - "--name"
      - risedev-meta
      - "--max-txn-ops"
      - "999999"
      - "--auto-compaction-mode"
      - periodic
      - "--auto-compaction-retention"
      - 1m
      - "--snapshot-count"
      - "10000"
    expose:
      - "2388"
    ports:
      - "2388:2388"
      - "2389:2389"
    depends_on: []
    volumes:
      - "etcd-0:/etcd-data"
    environment: {}
    container_name: etcd-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/2388
      interval: 1s
      timeout: 5s
      retries: 5
  frontend-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:nightly-20220620"
    command:
      - frontend-node
      - "--host"
      - "0.0.0.0:4566"
      - "--meta-addr"
      - "http://meta-node-0:5690"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "4566"
    ports:
      - "4566:4566"
    depends_on:
      - meta-node-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
    container_name: frontend-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/4566
      interval: 1s
      timeout: 5s
      retries: 5
  grafana-0:
    image: "grafana/grafana-oss:latest"
    command: []
    expose:
      - "3001"
    ports:
      - "3001:3001"
    depends_on: []
    volumes:
      - "grafana-0:/var/lib/grafana"
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana-risedev-datasource.yml:/etc/grafana/provisioning/datasources/grafana-risedev-datasource.yml"
      - "./grafana-risedev-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-risedev-dashboard.yml"
      - "./risingwave-dashboard.json:/risingwave-dashboard.json"
    environment: {}
    container_name: grafana-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/3001
      interval: 1s
      timeout: 5s
      retries: 5
  meta-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:nightly-20220620"
    command:
      - meta-node
      - "--listen-addr"
      - "0.0.0.0:5690"
      - "--host"
      - meta-node-0
      - "--dashboard-host"
      - "0.0.0.0:5691"
      - "--prometheus-host"
      - "0.0.0.0:1250"
      - "--backend"
      - etcd
      - "--etcd-endpoints"
      - "etcd-0:2388"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "5690"
      - "1250"
      - "5691"
    ports: []
    depends_on: []
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
    container_name: meta-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5690
      interval: 1s
      timeout: 5s
      retries: 5
  minio-0:
    image: "quay.io/minio/minio:latest"
    command:
      - server
      - "--address"
      - "0.0.0.0:9301"
      - "--console-address"
      - "0.0.0.0:9400"
      - /data
    expose:
      - "9301"
      - "9400"
    ports:
      - "9301:9301"
      - "9400:9400"
    depends_on: []
    volumes:
      - "minio-0:/data"
    entrypoint: "\n/bin/sh -c '\nset -e\nmkdir -p \"/data/hummock001\"\n/usr/bin/docker-entrypoint.sh \"$$0\" \"$$@\"\n'"
    environment:
      MINIO_CI_CD: "1"
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: "http://prometheus-0:9500"
      MINIO_ROOT_PASSWORD: hummockadmin
      MINIO_ROOT_USER: hummockadmin
    container_name: minio-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9301
      interval: 1s
      timeout: 5s
      retries: 5
  prometheus-0:
    image: "prom/prometheus:latest"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.listen-address=0.0.0.0:9500"
      - "--storage.tsdb.retention.time=30d"
    expose:
      - "9500"
    ports:
      - "9500:9500"
    depends_on: []
    volumes:
      - "prometheus-0:/prometheus"
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    environment: {}
    container_name: prometheus-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9500
      interval: 1s
      timeout: 5s
      retries: 5
  redpanda:
    image: "docker.vectorized.io/vectorized/redpanda:latest"
    command:
      - redpanda
      - start
      - "--smp"
      - "4"
      - "--reserve-memory"
      - 0M
      - "--memory"
      - 4G
      - "--overprovisioned"
      - "--node-id"
      - "0"
      - "--check=false"
      - "--kafka-addr"
      - "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092"
      - "--advertise-kafka-addr"
      - "PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092"
    expose:
      - "29092"
      - "9092"
    ports:
      - "9092:9092"
      - "9644:9644"
    depends_on: []
    volumes:
      - "redpanda:/var/lib/redpanda/data"
    environment: {}
    container_name: redpanda
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9092
      interval: 1s
      timeout: 5s
      retries: 5
volumes:
  etcd-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
  redpanda:
    external: false
name: risingwave-compose
