---
version: "3"
x-image: &image
  image: ${RW_IMAGE:-risingwavelabs/risingwave:v1.5.0}
services:
  risingwave-standalone:
    <<: *image
    command: "standalone --meta-opts=\" \
                    --listen-addr 0.0.0.0:5690 \
                    --advertise-addr 0.0.0.0:5690 \
                    --dashboard-host 0.0.0.0:5691 \
                    --prometheus-host 0.0.0.0:1250 \
                    --connector-rpc-endpoint 0.0.0.0:50051 \
                    --backend etcd \
                    --etcd-endpoints etcd-0:2388 \
                    --state-store hummock+gcs://<bucket-name> \
                    --data-directory hummock_001 \
                    --config-path /risingwave.toml\" \
                 --compute-opts=\" \
                    --config-path /risingwave.toml \
                    --listen-addr 0.0.0.0:5688 \
                    --prometheus-listener-addr 0.0.0.0:1222 \
                    --advertise-addr 0.0.0.0:5688 \
                    --async-stack-trace verbose \
                    --connector-rpc-endpoint 0.0.0.0:50051 \
                    #--parallelism 4 \
                    #--total-memory-bytes 8589934592 \
                    --role both \
                    --meta-address http://0.0.0.0:5690\" \
                 --frontend-opts=\" \
                   --config-path /risingwave.toml \
                   --listen-addr 0.0.0.0:4566 \
                   --advertise-addr 0.0.0.0:4566 \
                   --prometheus-listener-addr 0.0.0.0:2222 \
                   --health-check-listener-addr 0.0.0.0:6786 \
                   --meta-addr http://0.0.0.0:5690\" \
                 --compactor-opts=\" \
                   --listen-addr 0.0.0.0:6660 \
                   --prometheus-listener-addr 0.0.0.0:1260 \
                   --advertise-addr 0.0.0.0:6660 \
                   --meta-address http://0.0.0.0:5690\""
    expose:
      - "6660"
      - "1260"
      - "4566"
      - "5688"
      - "1222"
      - "5690"
      - "1250"
      - "5691"
      - "2222"
    ports:
      - "4566:4566"
      - "5690:5690"
      - "5691:5691"
      - "1222:1222"
      - "1250:1250"
      - "1260:1260"
      - "2222:2222"
    depends_on:
      - etcd-0
    env_file: multiple_object_storage.env
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: risingwave-standalone
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/6660; exit $$?;'
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5688; exit $$?;'
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/4566; exit $$?;'
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5690; exit $$?;'
      interval: 1s
      timeout: 5s
    restart: always
    deploy:
      resources:
        limits:
          memory: 28G
        reservations:
          memory: 28G
  etcd-0:
    extends:
      file: docker-compose.yml
      service: etcd-0
  grafana-0:
    extends:
      file: docker-compose.yml
      service: grafana-0
  prometheus-0:
    extends:
      file: docker-compose.yml
      service: prometheus-0
  message_queue:
    extends:
      file: docker-compose.yml
      service: message_queue
volumes:
  etcd-0:
    external: false
  grafana-0:
    external: false
  prometheus-0:
    external: false
  message_queue:
    external: false
