[server]
heartbeat_interval_ms = 1000
max_heartbeat_interval_secs = 600

[meta]

[batch]

[streaming]
barrier_interval_ms = 250
checkpoint_frequency = 10

[storage]
shared_buffer_capacity_mb = 4096
sstable_size_mb = 256
block_size_kb = 1024
bloom_false_positive = 0.01
data_directory = "hummock_001"
block_cache_capacity_mb = 4096
meta_cache_capacity_mb = 1024
object_store_use_batch_delete = true
