[package]
name = "rw_futures_util"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
pin-project-lite = { workspace = true }

[dev-dependencies]
tokio = { version = "1.44", features = ["full"] }

[lints]
workspace = true
