[package]
name = "sync-point"
version = "0.1.0"
edition = "2021"

[features]
sync_point = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
spin = "0.10"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = ["sync", "time"] }

[lints]
workspace = true
