[package]
name = "sync-point"
version = "0.1.0"
edition = "2021"

[features]
sync_point = []

[dependencies]
futures-util = "0.3"
spin = "0.10"
thiserror = "2"
tokio = { version = "0.2", package = "madsim-tokio", features = ["sync", "time"] }

[lints]
workspace = true
