[package]
name = "risingwave_common_secret"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }


[dependencies]
aws-lc-rs = { version = "1.6", default-features = false, features = ["aws-lc-sys"] }
anyhow = "1"
bincode = "1"
parking_lot = { workspace = true }
prost = { workspace = true }
risingwave_pb = { workspace = true }
serde = { version = "1" }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tracing = "0.1"

[dev-dependencies]
hex = "0.4"

[lints]
workspace = true
