[package]
name = "risingwave_expr"
description = "Core expression traits and function registry."
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-trait = "0.1"
auto_impl = "1"
await-tree = { workspace = true }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
const-currying = "0.0.4"
downcast-rs = "2.0"
easy-ext = "1"
educe = "0.6"
either = "1"
enum-as-inner = "0.6"
futures = "0.3"
futures-async-stream = { workspace = true }
futures-util = "0.3"
itertools = { workspace = true }
linkme = { workspace = true }
num-traits = "0.2"
parse-display = "0.10"
paste = "1"
prometheus = "0.14"
risingwave_common = { workspace = true }
risingwave_common_estimate_size = { workspace = true }
risingwave_expr_macro = { path = "../macro" }
risingwave_pb = { workspace = true }
smallvec = "1"
static_assertions = "1"
thiserror = "1"
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt-multi-thread",
    "macros",
] }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
expect-test = "1"

[lints]
workspace = true
