[package]
name = "global_stats_alloc"
version = "0.1-alpha"
edition = "2021"
description = "Global allocator with statistics"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dependencies]
stats_alloc = { version = "0.1", features = ["nightly"]}
tikv-jemallocator = { version = "0.5", features = ["background_threads_runtime_support", "profiling", "stats"] }
