[package]
name = "risingwave_common_metrics"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_impl = "1"
bytes = "1"
cfg-or-panic = "0.2"
clap = { workspace = true }
easy-ext = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
http = "1"
http-02 = { package = "http", version = "0.2" }
hyper = { version = "1" }
hyper-014 = { package = "hyper", version = "0.14", features = ["client"] }
hyper-util = { version = "0.1", features = ["client-legacy"] }
hytra = { workspace = true }
itertools = { workspace = true }
parking_lot = { workspace = true }
pin-project-lite = { workspace = true }
prometheus = { version = "0.14" }
rw_iter_util = { workspace = true }
rw_resource_util = { workspace = true }
serde = { version = "1", features = ["derive"] }
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio" }
tonic = { workspace = true }
tower-layer = "0.3.3"
tower-service = "0.3.3"
tracing = "0.1"
tracing-subscriber = "0.3.17"

[target.'cfg(not(madsim))'.dependencies]
http-body = "1"
[target.'cfg(target_os = "linux")'.dependencies]
procfs = { version = "0.17", default-features = false }
libc = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
darwin-libproc = { git = "https://github.com/risingwavelabs/darwin-libproc.git", rev = "a502be24bd0971463f5bcbfe035a248d8ba503b7" }
libc = "0.2"
mach2 = "0.4"

[lints]
workspace = true
