extend = "common.toml"

[env]
MINIO_SYSTEM = "${SYSTEM}"
MCLI_DOWNLOAD_BIN = "https://dl.min.io/client/mc/release/${MINIO_SYSTEM}/mc"
MINIO_DOWNLOAD_BIN = "https://dl.min.io/server/minio/release/${MINIO_SYSTEM}/minio"

[tasks.download-minio]
category = "MinIO"
dependencies = ["prepare"]
condition = { env_set = [ "ENABLE_MINIO" ] }
description = "Download and extract MinIO"
script = '''
#!@shell
set -e
if [ -f "${PREFIX_BIN}/minio" ]; then
    exit 0
fi
echo "MinIO Server not found, downloading"
wget ${WGET_EXTRA_PARAMETER} -O "${PREFIX_TMP}/minio" "${MINIO_DOWNLOAD_BIN}"
chmod +x "${PREFIX_TMP}/minio"
mv "${PREFIX_TMP}/minio" "${PREFIX_BIN}/minio"
'''

[tasks.download-mcli]
category = "MinIO"
dependencies = ["prepare"]
condition = { env_set = [ "ENABLE_MINIO" ] }
description = "Download and extract MinIO Client"
script = '''
#!@shell
set -e
if [ -f "${PREFIX_BIN}/mcli" ]; then
    exit 0
fi
echo "MinIO Client not found, downloading"
wget ${WGET_EXTRA_PARAMETER} -O "${PREFIX_TMP}/mcli" "${MCLI_DOWNLOAD_BIN}"
chmod +x "${PREFIX_TMP}/mcli"
mv "${PREFIX_TMP}/mcli" "${PREFIX_BIN}/mcli"
'''
