[package]
name = "workspace-static-link"
version = "0.1.12"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Use a feature flag to control enable or not, otherwise `cargo test` will compile all dependencies.
enabled = ["isahc", "openssl"]

[dependencies]
isahc = { version = "1", optional = true, default-features = false, features = ["static-ssl", "static-curl"] }
openssl = { version = "0.10", optional = true, features = ["vendored"] }
# workspace-hack = { version = "0.1", path = "../../workspace-hack" }
# Don't add workspace-hack into this crate!
