[server]
telemetry_enabled = false

[meta]
enable_compaction_deterministic = true
max_heartbeat_interval_secs = 600

[streaming]
in_flight_barrier_nums = 40

[storage]
shared_buffer_capacity_mb = 4096
block_cache_capacity_mb = 4096
meta_cache_capacity_mb = 1024
compactor_memory_limit_mb = 5120

[storage.file_cache]
capacity_mb = 1024
total_buffer_capacity_mb = 128
cache_file_fallocate_unit_mb = 512
cache_meta_fallocate_unit_mb = 16
cache_file_max_write_size_mb = 4

[system]
sstable_size_mb = 256
block_size_kb = 1024
bloom_false_positive = 0.001
data_directory = "hummock_001"
# We set a large checkpoint frequency to prevent the embedded meta node
# to commit new epochs to avoid bumping the hummock version during version log replay.
checkpoint_frequency = 99999999
barrier_interval_ms = 250
telemetry_enabled = false
