[meta]
disable_recovery = true
enable_committed_sst_sanity_check = true
max_heartbeat_interval_secs = 600

[streaming]
in_flight_barrier_nums = 10

[system]
barrier_interval_ms = 5000
checkpoint_frequency = 1