[meta]
disable_recovery = false
max_heartbeat_interval_secs = 60

# "local" is for Unix domain socket connections only
[[frontend.hba_config.entries]]
connection_type = "Local"
databases = ["all"]
users = ["all"]
auth_method = "trust"

# "host" is for TCP/IP connections, with standard auth for admin users
[[frontend.hba_config.entries]]
connection_type = "Host"
databases = ["all"]
users = ["root", "postgres", "rwadmin"]
addresses = ["0.0.0.0/0"]
auth_method = "password"

# "host" is for TCP/IP connections, with LDAP search+bind auth for test users
[[frontend.hba_config.entries]]
connection_type = "Host"
databases = ["all"]
users = ["testuser1"]
addresses = ["all"]
auth_method = "ldap"

[frontend.hba_config.entries.auth_options]
ldapserver = "ldap-server"
ldapscheme = "ldaps"
ldapport = "636"
# Search and bind configuration
ldapbasedn = "ou=people,dc=example,dc=com"
ldapsearchfilter = "(&(objectClass=person)(uid=$username))"
# Required for non-anonymous search
ldapbinddn = "cn=admin,dc=example,dc=com"
ldapbindpasswd = "admin123"

[streaming]
in_flight_barrier_nums = 10

[storage]
imm_merge_threshold = 2

[system]
barrier_interval_ms = 250
checkpoint_frequency = 5
max_concurrent_creating_streaming_jobs = 0
