[meta]
disable_recovery = true
max_heartbeat_interval_secs = 60

[streaming]
in_flight_barrier_nums = 10

[streaming.developer]
stream_exchange_concurrent_barriers = 10
stream_enable_arrangement_backfill = false

[batch]
enable_barrier_read = true

[storage]
share_buffers_sync_parallelism = 4
imm_merge_threshold = 2

[system]
barrier_interval_ms = 250
checkpoint_frequency = 5
max_concurrent_creating_streaming_jobs = 0
