[meta]
disable_recovery = true
max_heartbeat_interval_secs = 600

[meta.compaction_config]
level0_tier_compact_file_number = 6
level0_overlapping_sub_level_compact_level_count = 3
level0_max_compact_file_number = 96

[streaming]
in_flight_barrier_nums = 10

[streaming.developer]
stream_exchange_concurrent_barriers = 10

[storage]
imm_merge_threshold = 2

[system]
barrier_interval_ms = 250
checkpoint_frequency = 5

max_concurrent_creating_streaming_jobs = 0