---
services:
  risingwave-standalone:
    extends:
      file: ../../docker/docker-compose.yml
      service: risingwave-standalone
    volumes:
      - "../../gcp-rwctest.json:/gcp-rwctest.json"
  postgres-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: postgres-0
  grafana-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: grafana-0
  minio-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: minio-0
  prometheus-0:
    extends:
      file: ../../docker/docker-compose.yml
      service: prometheus-0
  gcloud-cli:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
    command: tail -f /dev/null
    volumes:
      - "../../gcp-rwctest.json:/gcp-rwctest.json"

volumes:
  risingwave-standalone:
    external: false
  postgres-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
  message_queue:
    external: false
name: risingwave-compose
