[package]
name = "risingwave_frontend_test_runner"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
console = "0.15"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
risingwave_frontend = { path = ".." }
risingwave_sqlparser = { path = "../../sqlparser" }
serde = { version = "1", features = ["derive"] }
serde_with = "1"
serde_yaml = "0.8"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
walkdir = "2"

[dev-dependencies]
tempfile = "3"

[build-dependencies]
anyhow = "1"
walkdir = "2"

[[bin]]
name = "planner-test-apply"
path = "src/bin/apply.rs"
