[workspace]
members = [
  "batch",
  "bench",
  "common",
  "connector",
  "frontend",
  "meta",
  "prost",
  "prost/helpers",
  "riselab",
  "rpc_client",
  "server",
  "source",
  "sqlparser",
  "storage",
  "stream",
  "tests/regress",
  "utils/memcomparable",
]

[profile.release]
panic = 'abort'
