comment_width = 120
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
normalize_comments = true
normalize_doc_attributes = true
reorder_imports = true
tab_spaces = 4
wrap_comments = true
