[book]
authors = ["xxchan"]
title = "RisingWave Developer Guide"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/risingwavelabs/risingwave/tree/main/docs/dev/src"
edit-url-template = "https://github.com/risingwavelabs/risingwave/edit/main/docs/dev/{path}"
search.use-boolean-and = true
mathjax-support = true

[output.linkcheck2]
