[package]
name = "risingwave_meta_model_migration"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
easy-ext = "1"
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tokio = { version = "0.2", package = "madsim-tokio" }