[tool.poetry]
name = "icelake-integration-tests"
version = "0.0.9"
description = ""
authors = ["Renjie Liu <liurenjie2008@gmail.com>"]
readme = "README.md"
packages = [{include = "icelake_integration_tests"}]

[tool.poetry.dependencies]
python = "^3.11"
pyspark = { version = "3.4.1", extras = ["sql", "connect"] }
psycopg2-binary = "^2.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
