[package]
name = "risingwave_hummock_trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12"
crossbeam = "0.8.1"
risingwave_common = { path = "../../common" }
tokio = { version = "0.2", package = "madsim-tokio" }
bincode = "=2.0.0-rc.2"
byteorder = "1"
anyhow = "1.0"
thiserror = "1.0"