[package]
name = "risingwave_hummock_trace"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
bincode = "=2.0.0-rc.2"
byteorder = "1"
crossbeam = "0.8.1"
parking_lot = "0.12"
risingwave_common = { path = "../../common" }
thiserror = "1.0"
tokio = { version = "0.2", package = "madsim-tokio" }

[dev-dependencies]
mockall = "0.11.2"
