[profile.default]
retries = 0
slow-timeout = { period = "5s" }
status-level = "all"
final-status-level = "slow"

[profile.ci]
retries = 0
failure-output = "immediate-final"
fail-fast = false

[profile.ci-sim]
retries = 0
slow-timeout = { period = "400s" }
status-level = "all"
failure-output = "immediate-final"
fail-fast = false

[profile.ci.junit]
path = "junit-nextest.xml"
report-name = "nextest-run"

[test-groups]
failpoint-limited = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(failpoint_limited::)'
test-group = 'failpoint-limited'

[[profile.ci.overrides]]
filter = 'test(failpoint_limited::)'
test-group = 'failpoint-limited'

[[profile.ci-sim.overrides]]
filter = 'test(failpoint_limited::)'
test-group = 'failpoint-limited'

[[profile.ci.junit.overrides]]
filter = 'test(failpoint_limited::)'
test-group = 'failpoint-limited'