[profile.default]
retries = 0
slow-timeout = { period = "5s" }
status-level = "all"
final-status-level = "slow"

[profile.ci]
retries = 0
failure-output = "immediate-final"
fail-fast = false

[profile.ci-sim]
retries = 0
slow-timeout = { period = "400s" }
status-level = "all"
failure-output = "immediate-final"
fail-fast = false

[profile.ci.junit]
path = "junit-nextest.xml"
report-name = "nextest-run"
