[env]
CARGO_MAKE_CRATE_INSTALLATION_LOCKED = true
RISEDEV = "1"
RUST_BACKTRACE = "1"
OS = { source = "${CARGO_MAKE_RUST_TARGET_OS}", mapping = { linux = "linux", macos = "darwin" } }
ARCH = { source = "${CARGO_MAKE_RUST_TARGET_ARCH}", mapping = { x86_64 = "amd64", aarch64 = "arm64" } }
SYSTEM = "${OS}-${ARCH}"
SYSTEM_UNDERSCORE = "${OS}_${ARCH}"
PREFIX = "${PWD}/.risingwave"
JAVA_DIR = "${PWD}/java"
PREFIX_USR_BIN = "${PWD}/.bin"
PREFIX_BIN = "${PREFIX}/bin"
PREFIX_CONFIG = "${PREFIX}/config"
PREFIX_DATA = "${PREFIX}/data"
PREFIX_LOG = "${PREFIX}/log"
PREFIX_TMP = "${PREFIX}/tmp"
PREFIX_DOCKER = "${PREFIX}/rw-docker"
PREFIX_PROFILING = "${PREFIX}/profiling"
PREFIX_SECRET = "${PREFIX}/secrets"

BUILD_MODE_DIR = { source = "${ENABLE_RELEASE_PROFILE}", default_value = "debug", mapping = { true = "release" } }
RISINGWAVE_BUILD_PROFILE = { source = "${ENABLE_RELEASE_PROFILE}", default_value = "dev", mapping = { true = "release" } }

[tasks.prepare-dir]
private = true
condition = { files_not_exist = [
    "${PREFIX}",
    "${PREFIX_BIN}",
    "${PREFIX_TMP}",
    "${PREFIX_DATA}",
    "${PREFIX_CONFIG}",
    "${PREFIX_CONFIG}/mcli",
    "${PREFIX_LOG}",
] }
script = '''
#!/usr/bin/env bash
echo "Using ${PREFIX} as base folder"
mkdir -p "${PREFIX}" "${PREFIX_BIN}" "${PREFIX_TMP}" "${PREFIX_DATA}" "${PREFIX_CONFIG}" "${PREFIX_CONFIG}/mcli" "${PREFIX_LOG}" "${PREFIX_PROFILING}"
'''

[tasks.check-risedev-configured]
private = true
condition = { env_not_set = [ "RISEDEV_CONFIGURED" ] }
script = '''
#!/usr/bin/env bash
set -e
echo "RiseDev is not configured, please run ${RISEDEV_CMD} configure"
exit 1
'''

[tasks.prepare]
private = true
category = "Misc"
description = "Create .risingwave folder for storing temporary files and data"
dependencies = ["prepare-dir", "check-risedev-configured"]
