extend = "common.toml"

[env]
RW_CONNECTOR_VERSION = "0.1.17"
RW_CONNECTOR_DOWNLOAD_PATH = "${PREFIX_TMP}/risingwave-connector-${RW_CONNECTOR_VERSION}.tar.gz"
RW_CONNECTOR_RELEASE = "risingwave-connector-${RW_CONNECTOR_VERSION}.tar.gz"
RW_CONNECTOR_BIN_PREFIX = "${PREFIX_BIN}/connector-node"

RW_CONNECTOR_DOWNLOAD_URL = "https://github.com/risingwavelabs/risingwave-connector-release/raw/main/risingwave-connector-${RW_CONNECTOR_VERSION}.tar.gz"

[tasks.download-connector]
category = "RiseDev - Components"
dependencies = ["prepare"]
condition = { env_set = [ "ENABLE_RW_CONNECTOR" ] }
description = "Download RisingWave Connector"
script = '''
#!/usr/bin/env bash
set -e
if [ -f "${RW_CONNECTOR_BIN_PREFIX}/start-service.sh" ]; then
    exit 0
fi

if [ -f "${RW_CONNECTOR_DOWNLOAD_PATH}" ]; then
    mkdir -p "${PREFIX_BIN}/connector-node"
    tar xf "${RW_CONNECTOR_DOWNLOAD_PATH}" -C "${PREFIX_BIN}/connector-node"
    rm "${RW_CONNECTOR_DOWNLOAD_PATH}"
else
    echo "RisingWave Connector not found, download ${RW_CONNECTOR_RELEASE}"
    curl -fL -o "${RW_CONNECTOR_DOWNLOAD_PATH}" "${RW_CONNECTOR_DOWNLOAD_URL}"
    mkdir -p "${PREFIX_BIN}/connector-node"
    tar xf "${RW_CONNECTOR_DOWNLOAD_PATH}" -C "${PREFIX_BIN}/connector-node"
    rm "${RW_CONNECTOR_DOWNLOAD_PATH}"
fi
'''
