extend = "common.toml"

[env]
ETCD_SYSTEM = "${SYSTEM}"
ETCD_VER = "v3.6.0-alpha.0" # Only v.3.6.0-alpha.0 supported darwin-arm64.
ETCD_DOWNLOAD_URL_LINUX = "https://github.com/etcd-io/etcd/releases/download/${ETCD_VER}/etcd-${ETCD_VER}-${ETCD_SYSTEM}.tar.gz"
ETCD_DOWNLOAD_URL_OTHER = "https://github.com/etcd-io/etcd/releases/download/${ETCD_VER}/etcd-${ETCD_VER}-${ETCD_SYSTEM}.zip"
ETCD_DOWNLOAD_PATH_LINUX = "${PREFIX_TMP}/etcd.tar.gz"
ETCD_DOWNLOAD_PATH_OTHER = "${PREFIX_TMP}/etcd.zip"
ETCD_RELEASE = "etcd-${ETCD_VER}-${ETCD_SYSTEM}"

[tasks.download-etcd]
private = true
category = "RiseDev - Components"
dependencies = ["prepare"]
condition = { env_set = [ "ENABLE_ETCD" ] }
description = "Download and extract Etcd"
script = '''
#!/usr/bin/env bash
set -e
if [ -d "${PREFIX_BIN}/etcd" ]; then
    exit 0
fi
echo "Etcd Server for $ETCD_SYSTEM not found, downloading"
if [ "$ETCD_SYSTEM" = "darwin-amd64" ] || [ "$ETCD_SYSTEM" = "darwin-arm64" ] || [ "$ETCD_SYSTEM" = "windows-amd64" ]; then
    curl -L "${ETCD_DOWNLOAD_URL_OTHER}" -o "${ETCD_DOWNLOAD_PATH_OTHER}"
    unzip "${ETCD_DOWNLOAD_PATH_OTHER}" -d "${PREFIX_TMP}"
else
    curl -L "${ETCD_DOWNLOAD_URL_LINUX}" -o "${ETCD_DOWNLOAD_PATH_LINUX}"
    tar -xf "${ETCD_DOWNLOAD_PATH_LINUX}" -C "${PREFIX_TMP}" --no-same-owner
fi

mv "${PREFIX_TMP}/${ETCD_RELEASE}" "${PREFIX_BIN}/etcd"

"${PREFIX_BIN}/etcd/etcd" --version
"${PREFIX_BIN}/etcd/etcdctl" version
"${PREFIX_BIN}/etcd/etcdutl" version
'''

[tasks.clean-etcd-data]
category = "Misc"
description = "Clean etcd data"
condition = { env_set = [ "PREFIX_DATA" ] }
script = '''
#!/usr/bin/env bash
set -e
rm -rf ${PREFIX_DATA}/etcd-*
'''
