extend = "common.toml"

[env]
GRAFANA_SYSTEM = "${SYSTEM_AMD64}"
GRAFANA_DOWNLOAD_PATH = "${PREFIX_TMP}/grafana.tar.gz"
GRAFANA_VERSION = "9.0.0"
GRAFANA_RELEASE = "grafana-${GRAFANA_VERSION}"
GRAFANA_DOWNLOAD_TAR_GZ = "https://dl.grafana.com/oss/release/${GRAFANA_RELEASE}.${GRAFANA_SYSTEM}.tar.gz"

[tasks.download-grafana]
category = "RiseDev - Components"
dependencies = ["prepare"]
condition = { env_set = [ "ENABLE_PROMETHEUS_GRAFANA" ] }
description = "Download and extract Grafana"
script = '''
#!/bin/bash
set -e
if [ -d "${PREFIX_BIN}/grafana" ]; then
    exit 0
fi
echo "Grafana not found, download ${GRAFANA_RELEASE}"
curl -fL -o "${GRAFANA_DOWNLOAD_PATH}" "${GRAFANA_DOWNLOAD_TAR_GZ}"
tar -xf "${GRAFANA_DOWNLOAD_PATH}" -C "${PREFIX_TMP}"
mv "${PREFIX_TMP}/${GRAFANA_RELEASE}" "${PREFIX_BIN}/grafana"
rm "${GRAFANA_DOWNLOAD_PATH}"
'''
