extend = "common.toml"

[env]
JAEGER_SYSTEM = "${SYSTEM}"
JAEGER_DOWNLOAD_PATH = "${PREFIX_TMP}/jaeger.tar.gz"
JAEGER_VERSION = "1.46.0"
JAEGER_RELEASE = "jaeger-${JAEGER_VERSION}-${JAEGER_SYSTEM}"
JAEGER_DOWNLOAD_TAR_GZ = "https://github.com/jaegertracing/jaeger/releases/download/v${JAEGER_VERSION}/${JAEGER_RELEASE}.tar.gz"

[tasks.download-jaeger]
private = true
category = "RiseDev - Components"
dependencies = ["prepare"]
condition = { env_set = [ "ENABLE_COMPUTE_TRACING" ] }
description = "Download and extract Jaeger"
script = '''
#!/usr/bin/env bash
set -e
if [ -d "${PREFIX_BIN}/jaeger" ]; then
    if [ -f "${PREFIX_BIN}/jaeger/RISEDEV-VERSION-${JAEGER_VERSION}" ]; then
        exit 0
    fi
fi
echo "Jaeger not found or outdated, download ${JAEGER_RELEASE}"
curl -fL -o "${JAEGER_DOWNLOAD_PATH}" "${JAEGER_DOWNLOAD_TAR_GZ}"
tar -xf "${JAEGER_DOWNLOAD_PATH}" -C "${PREFIX_TMP}"
rm -rf "${PREFIX_BIN}/jaeger"
mv "${PREFIX_TMP}/${JAEGER_RELEASE}" "${PREFIX_BIN}/jaeger"
rm "${JAEGER_DOWNLOAD_PATH}"
touch "${PREFIX_BIN}/jaeger/RISEDEV-VERSION-${JAEGER_VERSION}"
'''
