extend = "common.toml"

[env]
MINIO_SYSTEM = "${SYSTEM}"
MCLI_DOWNLOAD_BIN = { value = "https://dl.min.io/client/mc/release/${MINIO_SYSTEM}/mc", condition = { env_not_set = [ "MCLI_DOWNLOAD_BIN" ] } }
MINIO_DOWNLOAD_BIN = { value = "https://dl.min.io/server/minio/release/${MINIO_SYSTEM}/minio", condition = { env_not_set = [ "MINIO_DOWNLOAD_BIN" ] } }

[tasks.download-minio]
private = true
category = "RiseDev - Components"
dependencies = ["prepare"]
condition = { env_set = [ "ENABLE_MINIO" ] }
description = "Download and extract MinIO"
script = '''
#!/usr/bin/env bash
set -e
if [ -f "${PREFIX_BIN}/minio" ]; then
    exit 0
fi
echo "MinIO Server not found, downloading"
curl -fL -o "${PREFIX_TMP}/minio" "${MINIO_DOWNLOAD_BIN}"
chmod +x "${PREFIX_TMP}/minio"
mv "${PREFIX_TMP}/minio" "${PREFIX_BIN}/minio"

"${PREFIX_BIN}/minio" --version
'''

[tasks.download-mcli]
private = true
category = "RiseDev - Components"
dependencies = ["prepare"]
condition = { env_set = [ "ENABLE_MINIO" ] }
description = "Download and extract MinIO Client"
script = '''
#!/usr/bin/env bash
set -e
if [ -f "${PREFIX_BIN}/mcli" ]; then
    exit 0
fi
echo "MinIO Client not found, downloading"
curl -fL -o "${PREFIX_TMP}/mcli" "${MCLI_DOWNLOAD_BIN}"
chmod +x "${PREFIX_TMP}/mcli"
mv "${PREFIX_TMP}/mcli" "${PREFIX_BIN}/mcli"

"${PREFIX_BIN}/mcli" --version
'''
