[tasks.configure-if-not-configured]
condition = { env_not_set = [ "RISEDEV_CONFIGURED" ] }
script = '''
#!/bin/bash
set -e
ENV_PATH="$(pwd)/risedev-components.user.env"
cargo run --bin risedev-config -- -f "${ENV_PATH}" default
'''

[tasks.configure]
script = '''
#!/bin/bash
set -e
ENV_PATH="$(pwd)/risedev-components.user.env"
cargo run --bin risedev-config -- -f "${ENV_PATH}" "$@"
'''

[tasks.config]
alias = "configure"