[package]
name = "task_stats_alloc"
version = "0.1.11"
edition = "2021"
description = "Allocator with statistics"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]

[dependencies.tokio]
version = "0.2"
package = "madsim-tokio"
features = ["fs", "rt", "rt-multi-thread", "sync", "macros", "time", "signal"]

[dev-dependencies]

[target.'cfg(loom)' .dependencies]
loom = { version = "0.5", features = ["futures", "checkpoint"] }
