[package]
name = "risingwave_meta_node"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
clap = { workspace = true }
educe = "0.6"
either = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hex = "0.4"
itertools = { workspace = true }
otlp-embedded = { workspace = true }
prometheus-http-query = "0.8"
redact = "0.1.5"
regex = "1"
risingwave_common = { workspace = true }
risingwave_common_heap_profiling = { workspace = true }
risingwave_common_service = { workspace = true }
risingwave_meta = { workspace = true }
risingwave_meta_model_migration = { workspace = true }
risingwave_meta_service = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
sea-orm = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tonic = { workspace = true }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]

[lib]
test = false

[lints]
workspace = true
