[package]
name = "risingwave_common_heap_profiling"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["clock", "std"] }
parking_lot = { workspace = true }
risingwave_common = { workspace = true }
thiserror = { workspace = true }
thiserror-ext = { workspace = true }
tikv-jemalloc-ctl = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio" }
tracing = { workspace = true }

[lints]
workspace = true
