init_sqls = [
    'CREATE SCHEMA IF NOT EXISTS demo_db',
    'DROP TABLE IF EXISTS demo_db.demo_table',
    '''
    CREATE TABLE demo_db.demo_table (
    id int,
    v1 int,
    v2 long,
    v3 string
    ) USING iceberg
    PARTITIONED BY (v1,v2)
    TBLPROPERTIES ('format-version'='2');
    '''
]

slt = 'test_case/iceberg_sink_upsert.slt'

verify_schema = ['int','int','long','string']

verify_sql = 'SELECT * FROM demo_db.demo_table ORDER BY id, v1 ASC'

verify_data = """
1,1,50,1-50
1,2,2,2-2
1,3,2,3-2
1,5,2,5-2
1,8,2,8-2
1,13,2,13-2
1,21,2,21-2
"""

drop_sqls = [
 'DROP TABLE IF EXISTS demo_db.demo_table',
 'DROP SCHEMA IF EXISTS demo_db'
]
