[tasks.meta-backup-restore-test]
category = "RiseDev - Test"
description = "Run meta backup/restore test"
condition = { env_set = [ "PREFIX_BIN", "PREFIX_DATA" ] }
script = """
#!/bin/bash
set -e
rm -f "${PREFIX_BIN}/backup-restore"
ln -s "$(pwd)/target/${RISEDEV_BUILD_TARGET_DIR}${BUILD_MODE_DIR}/backup-restore" "${PREFIX_BIN}/backup-restore"
test_root="src/storage/backup/integration_tests"
BACKUP_TEST_PREFIX_BIN=${PREFIX_BIN} \
BACKUP_TEST_PREFIX_CONFIG=${PREFIX_CONFIG} \
bash "${test_root}/run_all.sh"
"""
