[package]
name = "risingwave_stream"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-recursion = "1"
async-stream = "0.3"
async-trait = "0.1"
auto_enums = { workspace = true }
await-tree = { workspace = true }
bytes = "1"
cfg-if = "1"
delta_btree_map = { path = "../utils/delta_btree_map" }
dhat = { version = "0.3", optional = true }
educe = "0.6"
either = "1"
enum-as-inner = "0.6"
fail = "0.5"
foyer = { workspace = true }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
hytra = "0.1.2"
iceberg = { workspace = true }
itertools = { workspace = true }
jsonbb = { workspace = true }
local_stats_alloc = { path = "../utils/local_stats_alloc" }
lru = { workspace = true }
maplit = "1.0.2"
memcomparable = "0.2"
multimap = "0.10"
parking_lot = { workspace = true }
pin-project = "1"
prehash = "1"
prometheus = { version = "0.14", features = ["process"] }
prost = { workspace = true }
rand = { workspace = true }
risingwave_common = { workspace = true }
risingwave_common_estimate_size = { workspace = true }
risingwave_common_rate_limit = { workspace = true }
risingwave_connector = { workspace = true }
risingwave_dml = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
risingwave_storage = { workspace = true }
rw_futures_util = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
smallvec = { workspace = true }
static_assertions = "1"
strum_macros = "0.27"
thiserror = "1"
thiserror-ext = { workspace = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
  "rt",
  "rt-multi-thread",
  "sync",
  "macros",
  "time",
  "signal",
  "fs",
] }
tokio-metrics = "0.4.0"
tokio-retry = "0.3"
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = "0.1"
url = "2"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
criterion = { workspace = true, features = ["async_tokio", "async"] }
expect-test = "1"
pretty_assertions = "1"
risingwave_expr_impl = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_hummock_test = { path = "../storage/hummock_test", features = [
  "test",
] }
serde_yaml = "0.9"
tracing-subscriber = "0.3.17"
tracing-test = "0.2"

[features]
dhat-heap = ["dhat"]

[[bench]]
name = "stream_hash_agg"
harness = false

[[bench]]
name = "bench_state_table"
harness = false

[[bench]]
name = "stream_hash_join_rt"
harness = false

[[bench]]
name = "stream_hash_join_mem"
harness = false

[lints]
workspace = true
