[package]
name = "risingwave_stream"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
async-recursion = "1"
async-stream = "0.3"
async-trait = "0.1"
auto_enums = "0.8"
await-tree = { workspace = true }
bytes = "1"
educe = "0.4"
either = "1"
enum-as-inner = "0.6"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = { workspace = true }
governor = { version = "0.6", default-features = false, features = [
    "std",
    "dashmap",
    "jitter",
] }
hytra = "0.1.2"
itertools = "0.11"
local_stats_alloc = { path = "../utils/local_stats_alloc" }
lru = { git = "https://github.com/risingwavelabs/lru-rs.git", rev = "cb2d7c7" }
maplit = "1.0.2"
memcomparable = "0.2"
multimap = "0.9"
parking_lot = "0.12"
pin-project = "1"
prometheus = { version = "0.13", features = ["process"] }
prost = { workspace = true }
rand = "0.8"
risingwave_common = { workspace = true }
risingwave_connector = { workspace = true }
risingwave_expr = { workspace = true }
risingwave_hummock_sdk = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
risingwave_source = { workspace = true }
risingwave_storage = { workspace = true }
serde_json = "1"
smallvec = "1"
static_assertions = "1"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-metrics = "0.3.0"
tokio-stream = "0.1"
tonic = { workspace = true }
tracing = "0.1"

[target.'cfg(enable_task_local_alloc)'.dependencies]
task_stats_alloc = { path = "../utils/task_stats_alloc" }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
assert_matches = "1"
criterion = { workspace = true, features = ["async_tokio", "async"] }
expect-test = "1"
risingwave_expr_impl = { workspace = true }
risingwave_hummock_test = { path = "../storage/hummock_test", features = [
    "test",
] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tracing-test = "0.2"

[[bench]]
name = "stream_hash_agg"
harness = false

[[bench]]
name = "bench_state_table"
harness = false

[lints]
workspace = true
