[package]
name = "risingwave_error"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
bincode = "1"
bytes = "1"
easy-ext = "1"
serde = "1"
serde-error = "0.1"
thiserror = "1"
thiserror-ext = { workspace = true }
tonic = { workspace = true }
tracing = "0.1"

[lints]
workspace = true
