[package]
name = "risingwave_common"
version = "0.1.8"
edition = "2021"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
auto_enums = "0.7"
byteorder = "1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
comfy-table = "6"
crc32fast = "1"
either = "1"
fail = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
hyper = "0.14"
itertools = "0.10"
lazy_static = "1"
log = "0.4"
lru = { git = "https://github.com/singularity-data/lru-rs.git", rev = "e0e9ddaf8e4a51c244a03676734437e68a336b30" }
madsim = "=0.2.0-alpha.3"
memcomparable = { path = "../utils/memcomparable" }
more-asserts = "0.3"
num-traits = "0.2"
paste = "1"
prometheus = { version = "0.13" }
prost = "0.10"
risingwave_pb = { path = "../prost" }
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
smallvec = "1"
spin = "0.9"
thiserror = "1"
tokio = { version = "=0.2.0-alpha.3", package = "madsim-tokio", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal"] }
tokio-stream = "0.1"
toml = "0.5"
tonic = { version = "=0.2.0-alpha.3", package = "madsim-tonic" }
tower = { version = "0.4", features = ["util", "load-shed"] }
tower-http = { version = "0.3", features = ["add-extension", "cors"] }
tracing = { version = "0.1" }
twox-hash = "1"
url = "2"
value-encoding = { path = "../utils/value-encoding" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
rand = "0.8"
