
[tasks.update-planner-test]
description = "Update planner test data"
private = true
script = '''
#!/bin/bash
set -e
cargo run --bin planner-test-apply
cd src/frontend/test_runner/tests/testdata/

for f in *.apply.yaml
do
  yq -N -I4 -i '.. style=""' "$f"
done
'''

[tasks.apply-planner-test]
description = "Generate planner test data"
dependencies = [
  "update-planner-test"
]
script = '''
#!/bin/bash
set -e
cd src/frontend/test_runner/tests/testdata/

for f in *.apply.yaml
do
  diff "$f" "$(basename "$f" .apply.yaml).yaml" || true
done

echo "If you want to apply the planner test data, run: $(tput setaf 2)./risedev do-apply-planner-test$(tput sgr 0)"
'''
category = "RiseDev - Test"

[tasks.do-apply-planner-test]
description = "Apply planner test data"
dependencies = [
  "update-planner-test"
]
script = '''
#!/bin/bash
set -e
cd src/frontend/test_runner/tests/testdata/

for f in *.apply.yaml
do
  SOURCE="$(basename $f .apply.yaml).yaml"
  sed -i '1i# This file is formatted and updated by running the task `./risedev do-apply-planner-test`.\n' "$f"
  if [ -f "$SOURCE" ]; then
    cp "$f" "$SOURCE"
  fi
done

rm *.apply.yaml

echo "$(tput setaf 2)Diff applied!$(tput sgr 0)"
'''
category = "RiseDev - Test"

[tasks.run-planner-test]
description = "Run planner test"
category = "RiseDev - Test"
dependencies = ["warn-on-missing-tools"]
script = '''
#!/bin/bash
set -e

cargo nextest run -p risingwave_frontend_test_runner "$@"
'''
