[package]
name = "arrow-udf-runtime"
version = "0.8.0"
description = "Runtime for Arrow UDFs."
keywords = ["arrow", "udf", "runtime"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/risingwavelabs/arrow-udf"

[features]
default = ["wasm", "python", "javascript", "remote"]
embedded = ["wasm", "python", "javascript"]

wasm = ["wasm-runtime", "wasm-build"]
python = ["python-runtime"]
javascript = ["javascript-runtime", "javascript-fetch"]
remote = ["remote-runtime"]

wasm-runtime = ["dep:wasi-common", "dep:wasmtime", "dep:genawaiter2"]
wasm-build = ["dep:tempfile"]
python-runtime = ["dep:pyo3"]
javascript-runtime = ["dep:atomic-time", "dep:rquickjs"]
javascript-fetch = ["dep:reqwest", "dep:serde_json"]
remote-runtime = ["dep:arrow-flight", "dep:tonic", "dep:tracing"]

[dependencies]
anyhow = "1"
arrow-array = "54"
arrow-buffer = "54"
arrow-ipc = "54"
arrow-schema = "54"
arrow-select = "54"
async-trait = "0.1"
base64 = "0.22"
itertools = "0.14"
futures-util = "0.3"
tokio = { version = "1", features = ["time", "test-util", "macros"] }
thiserror = "2"

wasi-common = { version = "36.0.3", optional = true }
wasmtime = { version = "36.0.3", optional = true }
genawaiter2 = { version = "0.100.1", optional = true }
tempfile = { version = "3", optional = true }

pyo3 = { version = "0.24.1", optional = true, features = ["auto-initialize"] }

atomic-time = { version = "0.1", optional = true }
rquickjs = { version = "0.6", features = [
    "array-buffer",
    "parallel",
    "futures",
    "macro",
    "loader",
], optional = true }
reqwest = { version = "0.12", features = ["json"], optional = true }
serde_json = { version = "1", optional = true }

arrow-flight = { version = "54", optional = true }
tonic = { version = "0.13", optional = true }
tracing = { version = "0.1", optional = true }

[build-dependencies]
pyo3-build-config = { version = "0.24", features = ["resolve-config"] }

[dev-dependencies]
arrow-cast = { version = "54", features = ["prettyprint"] }
arrow-select = "54"
expect-test = "1"
tokio-test = "0.4"
mockito = "1.6.1"

[[test]]
name = "remote"
test = false
