name: Assign milestone

on:
  issues:
    types: [opened]

jobs:
  assign-milestone:
    runs-on: ubuntu-latest
    steps:
    - name: Add issue to the latest milestone
      uses: fuyufjh/automatically-set-milestone-to-issue@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-prefix: 'release-'
        version-separator: '.'
        overwrite: false
