name: Assign milestone

on:
  issues:
    types: [opened]

jobs:
  assign-milestone:
    runs-on: ubuntu-latest
    steps:
    - name: Automatically set milestone to issue
      uses: cgetc/automatically-set-milestone-to-issue@v0.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        version-prefix: 'release-'
        version-separator: '.'
