name: Deploy Developer Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  RUSTDOCFLAGS: "--markdown-css rust.css --markdown-no-toc --index-page /home/runner/work/risingwave/risingwave/docs/rustdoc/index.md -Zunstable-options"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          root-reserve-mb: 10240
          temp-reserve-mb: 10240
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        run: rustup show
      - name: Install dependencies for compiling RisingWave
        run: sudo apt-get update && sudo apt-get install -y make build-essential cmake protobuf-compiler curl openssl libssl-dev libsasl2-dev libcurl4-openssl-dev pkg-config postgresql-client tmux lld
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
        with:
          version: "v0.5.2"
      - name: build rustdocs
        run: |
          cargo doc --workspace --no-deps --document-private-items
          cp docs/rustdoc/rust.css target/doc/rust.css

          mkdir -p artifact/rustdoc
          cp -R target/doc/* artifact/rustdoc
      - name: Show available storage
        run: df -h
      - name: Install tools for building docs
        uses: taiki-e/install-action@v2
        with:
          tool: mdbook,mdbook-toc,mdbook-linkcheck
      - name: build developer doc
        run: |
          cd docs/dev
          mdbook build
          cp -R book/html/* ../../artifact
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: artifact
      - name: Show available storage
        run: df -h
  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
