name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 1 * * *'
  workflow_dispatch:
    inputs:
      # https://github.com/marketplace/actions/close-stale-issues#operations-per-run
      operationsPerRun:
        description: 'Max number of operations per run'
        required: true
        default: 30

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v10
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been open for 60 days with no activity.

          If you think it is still relevant today, and needs to be done *in the near future*, you can comment to update the status, or just manually remove the `no-issue-activity` label.

          You can also confidently close this issue as not planned to keep our backlog clean.
          Don't worry if you think the issue is still valuable to continue in the future.
          It's searchable and can be reopened when it's time. üòÑ
        stale-pr-message: |
          This PR has been open for 60 days with no activity.

          If it's blocked by code review, feel free to ping a reviewer or ask someone else to review it.

          If you think it is still relevant today, and have time to work on it *in the near future*, you can comment to update the status, or just manually remove the `no-pr-activity` label.

          You can also confidently close this PR to keep our backlog clean. (If no further action taken, the PR will be automatically closed after 7 days. Sorry!  üôè)
          Don't worry if you think the PR is still valuable to continue in the future.
          It's searchable and can be reopened when it's time. üòÑ
        close-pr-message: |
          Close this PR as there's no further actions taken after it is marked as stale for 7 days. Sorry! üôè

          You can reopen it when you have time to continue working on it.
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-close: -1
        days-before-pr-close: 7
        operations-per-run: ${{ github.event.inputs.operationsPerRun || 30 }}
        enable-statistics: true
